include ~/.config/omarchy/rurrent/theme/kitty.conf

# Font
font_family JetBrainsMonoNL Nerd Font
bold_italic_font auto
font_size        12.0

# Window
window_padding_width 14
# window_padding_height 14
window_margin_width 5
hide_window_decorations yes
# show_window_resize_notification no
confirm_os_window_close 0

# by default the new window will be side by side
enabled_layouts tall, stack
# Keybindings
map ctrl+shift+s goto_layout stack
map ctrl+shift+z last_used_layout

# used with nvim kitty navigator
map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right
map --when-focus-on var:IS_VIM=true ctrl+h
map --when-focus-on var:IS_VIM=true ctrl+j
map --when-focus-on var:IS_VIM=true ctrl+k
map --when-focus-on var:IS_VIM=true ctrl+l

allow_remote_control yes
listen_on unix:@mykitty

# ui 
background_opacity 0.7
background_blur 1
# map ctrl+insert copy_to_clipboard
# map shift+insert paste_from_clipboard
# map ctrl+shift+f2 "nvim ~/.config/kitty/kitty.conf"
# Allow remote access
# single_instance yes
# allow_remote_control yes

# Aesthetics
cursor_shape block
cursor_trail 100
enable_audio_bell no

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
